version: "3.9"

services:
#  database:
#    container_name: database
#    restart: "always"
#    build:
#      context: ./database
#      dockerfile: Dockerfile
#    env_file:
#      - "./database/.env"
#    platform: linux/x86_64
#    volumes:
#      - mysql-data:/var/lib/mysql
#    networks:
#      - app-network
#
  core:
    container_name: core
    restart: "always"
    build:
      context: ./backend
      dockerfile: ./services/core/Dockerfile
    ports:
      - "8080:8080"
#    depends_on:
#      - database
    networks:
      - app-network

  auth:
    container_name: authorization
    restart: "always"
    build:
      context: ./backend
      dockerfile: ./services/auth/Dockerfile
    ports:
      - "8081:8081"
#    depends_on:
#      - core
#      - database
    networks:
      - app-network

#  frontend:
#    container_name: frontend
#    restart: "always"
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "80:3000"
#    depends_on:
#      - core
#    networks:
#      - app-network

networks:
  app-network:

volumes:
  mysql-data: